### ISSUE TITLE
[Feature Request] EditorResponse should be a container type EditorReponse<A>

### ISSUE THREAD

**Issue by seancrowe** [chili-publish/editor-sdk#131]
## Is your feature request related to a problem? Please describe.
The documentation is almost useless as most API methods return `EditorResponse`, but we have no clue what `EditorResponse` actually contains.

Without knowing the output type, there is actually no benefit from using TypeScript as all output is hidden by the type `EditorResponse`.

## Describe the solution you'd like
The answer is to use generics, so that we can clearly define what `EditorResponse`  is wrapped around.

So we would write our type like this
```typescript
type EditorResponse<A> = {
    success: boolean;
    status: number;
    data?: string;
    error?: string;
    getData: () => A;
}
```

The type has a generic `<A>` which means we can identify the data type that is suppose to be wrapped in ` EditorResponse<A>` if things succeed.

Then we write type signatures to be explicit like for example getFrames would become
```
getFrames(): Promise<EditorResponse<FrameType>>
```

Now is very clear what the result of `getFrames()` returns if successful. There is no testing to try and figure out, it is very clear.
<br/>

You will also notice `EditorResponse<A>` requires a new function `getData()`. This function would return to you the data `A` if `EditorResponse<A>` is both successful and the JSON parse succeeds.

We can imagine a class that could be used for our framework:
```typescript
class EditorResponseObj<A> implements EditorResponse<A>{

    constructor(public success:boolean, public status:number, public data?:string, public error?:string) {}

   // This function will throw an exception if the parse fails or success is not true
    getData() {
        if (this.success == true && this.data != null) {
            return JSON.parse(this.data) as A;
        }
        else {
            throw  "Not Successful: " + this.error
        }
    }

}
```

### Secondary Benefit
There is also a secondary benefit besides being very clear on the type. This other benefit is we can get rid of boilerplate of writing the whole success checking and then JSON parsing over and over again.

So this:
```javascript
const respGetFrames = await sdk.frame.getFrames();

if (respGetFrames.success == true) {
    
    try {
        const frames = JSON.parse(respGetFrames.data);
    
        const wantedFrame = someMethodToFindAFrame(frames);
    
        const respSetName = await sdk.frame.setFrameName(wantedFrame.frameId, "New Name");
        
        if (respGetFrames.success == true) {
            
            // Do stuff
            
        }
        else {
            console.log(respGetFrames.error)
        }
        
        
        
    }
    catch(e) {
        console.log("Error:" + e)
    }
}
else {
    console.log(respGetFrames.error)
}
```

would be come this:
```javascript
try {
    const respGetFrames = (await sdk.frame.getFrames()).getData();
    const wantedFrame = someMethodToFindAFrame(frames);
    const respSetName = (await sdk.frame.setFrameName(wantedFrame.frameId, "New Name").getData());
}
catch(e) {
    console.log(e);
}
```

That is much more elegant 🥳

## Summary
So by adding in a generic in the `EditorResponse<A>` type with a `getData()` method, we can
* make the documentation more explicit for people to know the expected (possible) result from a successful `EditorResponse<A>`
* make working with `EditorResponse<A>` more elegant and get ride of boilerplate

----
By the way, I hate exceptions, but that is what JavaScript was built around. So we are just using JavaScript native error handling.

**Comment by brapoprod** [comment]
We're going to take this up in our next sprint.
Internal link to ticket https://support.chili-publish.com/browse/WRS-807

**Comment by seancrowe** [comment]
@brapoprod 
I suggested `getData()` in my original suggestion. However, I think a better name is `parseData()` as it implies that we are doing something to the data and indeed we are parsing the data.

**Comment by brapoprod** [comment]
https://github.com/chili-publish/editor-sdk/pull/138
